# Generated by Django 4.0.1 on 2022-01-31 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('specie', models.CharField(max_length=300)),
                ('weight', models.IntegerField()),
                ('length', models.IntegerField()),
                ('long', models.DecimalField(blank=True, decimal_places=3, max_digits=8)),
                ('lat', models.DecimalField(blank=True, decimal_places=3, max_digits=8)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Creation date')),
                ('image', models.ImageField(upload_to='media')),
            ],
        ),
    ]
